/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./public/index.html", "./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {
            colors: {
                contrast: "rgb(var(--contrast) / <alpha-value>)",
                slate: {
                    50: "rgb(var(--slate-50) / <alpha-value>)",
                    100: "rgb(var(--slate-100) / <alpha-value>)",
                    200: "rgb(var(--slate-200) / <alpha-value>)",
                    300: "rgb(var(--slate-300) / <alpha-value>)",
                    400: "rgb(var(--slate-400) / <alpha-value>)",
                    500: "rgb(var(--slate-500) / <alpha-value>)",
                    600: "rgb(var(--slate-600) / <alpha-value>)",
                    700: "rgb(var(--slate-700) / <alpha-value>)",
                    800: "rgb(var(--slate-800) / <alpha-value>)",
                    900: "rgb(var(--slate-900) / <alpha-value>)",
                },
                indigo: {
                    50: "rgb(var(--indigo-50) / <alpha-value>)",
                    100: "rgb(var(--indigo-100) / <alpha-value>)",
                    200: "rgb(var(--indigo-200) / <alpha-value>)",
                    300: "rgb(var(--indigo-300) / <alpha-value>)",
                    400: "rgb(var(--indigo-400) / <alpha-value>)",
                    500: "rgb(var(--indigo-500) / <alpha-value>)",
                    600: "rgb(var(--indigo-600) / <alpha-value>)",
                    700: "rgb(var(--indigo-700) / <alpha-value>)",
                    800: "rgb(var(--indigo-800) / <alpha-value>)",
                    900: "rgb(var(--indigo-900) / <alpha-value>)",
                },
                emerald: {
                    50: "rgb(var(--emerald-50) / <alpha-value>)",
                    100: "rgb(var(--emerald-100) / <alpha-value>)",
                    200: "rgb(var(--emerald-200) / <alpha-value>)",
                    400: "rgb(var(--emerald-400) / <alpha-value>)",
                    500: "rgb(var(--emerald-500) / <alpha-value>)",
                    600: "rgb(var(--emerald-600) / <alpha-value>)",
                    700: "rgb(var(--emerald-700) / <alpha-value>)",
                },
                amber: {
                    50: "rgb(var(--amber-50) / <alpha-value>)",
                    100: "rgb(var(--amber-100) / <alpha-value>)",
                    200: "rgb(var(--amber-200) / <alpha-value>)",
                    400: "rgb(var(--amber-400) / <alpha-value>)",
                    500: "rgb(var(--amber-500) / <alpha-value>)",
                    600: "rgb(var(--amber-600) / <alpha-value>)",
                    700: "rgb(var(--amber-700) / <alpha-value>)",
                },
                rose: {
                    50: "rgb(var(--rose-50) / <alpha-value>)",
                    100: "rgb(var(--rose-100) / <alpha-value>)",
                    200: "rgb(var(--rose-200) / <alpha-value>)",
                    400: "rgb(var(--rose-400) / <alpha-value>)",
                    500: "rgb(var(--rose-500) / <alpha-value>)",
                    600: "rgb(var(--rose-600) / <alpha-value>)",
                    700: "rgb(var(--rose-700) / <alpha-value>)",
                },
                sky: {
                    50: "rgb(var(--sky-50) / <alpha-value>)",
                    100: "rgb(var(--sky-100) / <alpha-value>)",
                    200: "rgb(var(--sky-200) / <alpha-value>)",
                    400: "rgb(var(--sky-400) / <alpha-value>)",
                    600: "rgb(var(--sky-600) / <alpha-value>)",
                    700: "rgb(var(--sky-700) / <alpha-value>)",
                },
                blue: {
                    400: "rgb(var(--blue-400) / <alpha-value>)",
                    500: "rgb(var(--blue-500) / <alpha-value>)",
                    600: "rgb(var(--blue-600) / <alpha-value>)",
                },
            },
        },
    },
    plugins: [],
};
